### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by david-lindner**
Use travis for testing as of #13 and generalize toy gridworld array dtype, see #16

### CODE REVIEW

**Comment by alok** [comment]
I thought the version for this was 3.5 rather than 3.6, something to do with google cloud? @jvmancuso you told me about this earlier

**Comment by david-lindner** [comment]
Ah good point, I am not sure about that. I have been using 3.6, because it was set in the `safe-grid-agents` `.travis.yml`. So this would have to be changed as well

**Comment by alok** [comment]
I'd wait for @jvmancuso to weigh in before changing anything since gcp may have finally updated to 3.6

**Comment by jvmncs** [comment]
3.5 is the current default on GCP still -- see here for an example: https://cloud.google.com/deep-learning-vm/docs/images
similarly, ML engine allows options for 2.7 or 3.5, but not 3.6 or 3.7

**Comment by david-lindner** [comment]
Apparently `black` only supports python 3.6+, which is unfortunate. My solution is pretty hacky: running travis for 3.5 without black and for 3.6 with black, but I guess it works.

**Pull request merged**
